AT-PHPIntership/booking-clinic

- app/Admin.php
- database/migrations/2018_07_20_030248_create_admins_table.php
- database/seeds/AdminsTableSeeder.php
Design Admin table, create Admin model, make migration and create seeder.
#{3}
YES 
-
> [Database]Design Admin Table, create model, migration, seeder

- public/css/admin/dashboard.css
- public/css/bootstrap.css
- resources/views/admin/dashboard.blade.php
- resources/views/admin/layouts/app.blade.php
- resources/views/admin/layouts/partials/navbar.blade.php
- resources/views/admin/layouts/partials/sidebar.blade.php
- routes/web.php
Add Admin layout template.
#2 
NO
-
> add admin dashboard template

- .circleci/config.yml
- app/Console/Kernel.php
- app/Exceptions/Handler.php
- app/Http/Controllers/Auth/RegisterController.php
- app/Http/Middleware/RedirectIfAuthenticated.php
- composer.json
- composer.lock
- phpcs.xml
- phpmd.xml
- `.circleci/config.yml`: config circeci to check every PR
- Install phpcs
- Install phpmd
- Fix some default Laravel code to pass phpcs
- Docs: https://github.com/squizlabs/PHP_CodeSniffer
- Rules set: `phpcs.xml`
- Command: `./vendor/bin/phpcs -n --standard=phpcs.xml`
- Docs: https://phpmd.org/
- Rules set: `phpmd.xml`
- Command: `./vendor/bin/phpmd app text phpmd.xml`
> config circleci check

- app/Http/Controllers/Admin/UserController.php
- app/User.php
- resources/lang/en/admin/user.php
- resources/views/admin/users/index.blade.php
- resources/views/admin/users/show.blade.php
- Add view show user
- Show user detail
NO
-
> view detail user

- app/Clinic.php
- app/ClinicType.php
- app/Http/Controllers/Admin/ClinicController.php
- database/factories/ClinicFactory.php
- database/migrations/2018_07_24_135121_create_clinics_table.php
- database/seeds/ClinicTableSeeder.php
- database/seeds/DatabaseSeeder.php
- resources/lang/en/admin/clinic.php
- resources/views/admin/clinics/index.blade.php
- resources/views/admin/layouts/partials/sidebar.blade.php
- routes/web.php
- Create migration, seeder, model clinics.
- Layout admin manage clinic.
- Implement and show list clinics 
YES
> Database clinics

- app/Clinic.php
- app/Http/Controllers/Admin/ClinicController.php
- app/Http/Requests/Admin/ClinicRequest.php
- resources/lang/en/admin/clinic.php
- resources/lang/en/admin/layout.php
- resources/views/admin/clinics/create.blade.php
- resources/views/admin/clinics/index.blade.php
- resources/views/admin/layouts/app.blade.php
- resources/views/admin/users/index.blade.php
> admin  add clinic

- app/Http/Controllers/Admin/ClinicTypeController.php
- app/Http/Requests/Admin/ClinicTypeRequest.php
- resources/lang/en/admin/clinic_type.php
- resources/views/admin/clinic_types/edit.blade.php
- resources/views/admin/clinic_types/index.blade.php
- resources/views/admin/layouts/app.blade.php
- routes/web.php
- Admin edit a clinic type.
- After update, redirect to list clinic_type page.
- Fix flash message in store action of ClinicTypeController..
NO
list all clinic_types #8
> Admin edit clinic types

- app/Admin.php
- app/Exceptions/Handler.php
- app/Http/Controllers/Admin/Auth/ForgotPasswordController.php
- app/Http/Controllers/Admin/Auth/LoginController.php
- app/Http/Controllers/Admin/Auth/RegisterController.php
- app/Http/Controllers/Admin/Auth/ResetPasswordController.php
- app/Http/Controllers/HomeController.php
- app/Http/Kernel.php
- app/Http/Middleware/AdminMiddleware.php
- app/Http/Middleware/RedirectIfAuthenticated.php
- config/auth.php
- resources/views/admin/auth/login.blade.php
- resources/views/admin/auth/passwords/email.blade.php
- resources/views/admin/auth/passwords/reset.blade.php
- resources/views/admin/auth/register.blade.php
- resources/views/admin/layouts/partials/navbar.blade.php
- resources/views/home.blade.php
- resources/views/layouts/app.blade.php
- routes/web.php
- Login admin function
- When admin access dashboard page or something on admin pages, he/she will be directed to admin login page.
- When admin authenticated system, it will be directed instantly to admin dashboard.
- After logout, browser will return to admin login page.
#3 
NO
-
> Login admin function

- app/Http/Controllers/Admin/ClinicTypeController.php
- public/js/admin/dashboard.js
- resources/lang/en/admin/clinic_type.php
- resources/lang/en/admin/layout.php
- resources/views/admin/clinic_types/create.blade.php
- resources/views/admin/clinic_types/edit.blade.php
- resources/views/admin/clinic_types/index.blade.php
- resources/views/admin/layouts/app.blade.php
- resources/views/admin/layouts/partials/block-flash.blade.php
- Show pop confirm action delete. 
- Delete and redirect to list clinic_types page
NO
list all clinic_type #8 
> Admin delete clinic types

- app/Http/Controllers/Admin/ClinicController.php
- app/Http/Requests/Admin/ClinicRequest.php
- database/factories/ClinicFactory.php
- resources/lang/en/admin/clinic.php
- resources/views/admin/clinics/edit.blade.php
- resources/views/admin/clinics/index.blade.php
- resources/views/admin/layouts/partials/sidebar.blade.php
Edit a clinic page for admin
NO
-
> Admin edit clinic

- app/Http/Controllers/Admin/ClinicController.php
- resources/lang/en/admin/clinic.php
- resources/views/admin/clinics/index.blade.php
- Create button .
- Show pop confirm action delete.
- Delete and redirect current page.
NO
-
> admin delete clinic

- tests/Browser/Admin/Clinic/UpdateClinicTest.php
- tests/Browser/Pages/Admin/Clinic/UpdateClinicPage.php
test dusk for updating clinic page on Admin role
NO
-
> test dusk for updating clinic [Admin]

- tests/Browser/Admin/Clinic/DeleteClinicTest.php
- tests/Browser/Pages/Admin/Clinic/ListClinicPage.php
- Dusk test case for deleting a clinic in admin page
NO
-
> test delete clinic [Admin]

- app/helpers.php
- composer.json
- config/app.php
- resources/lang/en/admin_clinic/dashboard.php
- resources/lang/en/admin_clinic/layout.php
- resources/views/admin/layouts/partials/sidebar.blade.php
- resources/views/admin_clinic/dashboard.blade.php
- resources/views/admin_clinic/layouts/app.blade.php
- resources/views/admin_clinic/layouts/partials/block-flash.blade.php
- resources/views/admin_clinic/layouts/partials/navbar.blade.php
- resources/views/admin_clinic/layouts/partials/sidebar.blade.php
- Create admin clinic dashboard page.
#{issue_id}
NO
-
> Admin clinic dashboard page

- resources/views/admin/clinics/show.blade.php
- resources/views/layouts/partials/carousel.blade.php
- tests/Browser/Admin/Clinic/ShowClinicTest.php
- tests/Browser/Pages/Admin/Clinic/ShowClinicPage.php
- modify page show detail clinic for better look
- test show detail clinic
NO
> test-show-detail-clinic

- app/Appointment.php
- app/Clinic.php
- app/User.php
- database/factories/AppointmentFactory.php
- database/migrations/2018_08_01_180746_create_appointments_table.php
- database/seeds/AppointmentTableSeeder.php
- database/seeds/DatabaseSeeder.php
- Create appointment migrate.
- Create appointment model, add relationship with clinics and users.
- Create appointment seeder.
YES 
-
> Create Appointments migrate

- app/Admin.php
- app/Http/Controllers/Admin/Auth/LoginController.php
- app/Http/Controllers/HomeController.php
- app/Http/Kernel.php
- app/Http/Middleware/ClinicAdminMiddleware.php
- database/factories/AdminFactory.php
- database/seeds/AdminsTableSeeder.php
- resources/views/admin_clinic/layouts/partials/navbar.blade.php
- resources/views/layouts/app.blade.php
- routes/web.php
Add AdminClinic middleware 
NO
-
> clinic admin login

- app/Appointment.php
- app/Http/Controllers/Admin/Auth/RegisterController.php
- app/Http/Controllers/AdminClinic/CalendarController.php
- composer.json
- composer.lock
- config/app.php
- resources/lang/en/admin_clinic/calendar.php
- resources/views/admin_clinic/calendar/index.blade.php
- resources/views/admin_clinic/layouts/app.blade.php
- resources/views/admin_clinic/layouts/partials/sidebar.blade.php
- routes/web.php
- storage/debugbar/.gitignore
- Add apointment calendar
- Rediect to clinic admin page after register
NO
-
> Add calendar appointment

- app/Appointment.php
- app/Examination.php
- database/factories/ExaminationFactory.php
- database/migrations/2018_08_07_031709_create_examinations_table.php
- database/seeds/DatabaseSeeder.php
- database/seeds/ExaminationsTableSeeder.php
add Migration, model, seeder for examinations
YES 
-
> add examination table

- .env.dusk.local
- app/Http/Requests/Admin/ClinicRequest.php
- app/Http/Requests/AdminClinic/ClinicRequest.php
- tests/Browser/Admin/Clinic/CreateClinicTest.php
change clinic's address to `required`
NO
-
> change validate in clinic request

- app/Traits/apiResponser.php
- docs/api-references/list_clinic_type.md
- Fix apiResponse file
- Fix api doc get list clinic types
#51 
NO
-
> fix apiResponse

- .circleci/config.yml
- tests/Feature/API/ClinicTypeTest.php
- tests/Feature/ExampleTest.php
Test API get list clinic types
-
> Test api get list clinic types

- app/Clinic.php
- app/Http/Controllers/API/User/ClinicController.php
- docs/api-references/clinic.md
- routes/api.php
Api get list clinic with sort
NO
-
> Api get list clinic

- tests/Feature/API/UserRegisterTest.php
- tests/TestCase.php
Test api user register
#52 
NO
-
> Test api user register

- tests/Feature/API/UserLoginTest.php
- tests/TestCase.php
- Test api user login
- Task ID: TI-1
NO
-
> Test api user login

- composer.json
- composer.lock
- config/breadcrumbs.php
- resources/lang/en/admin/breadcrumb.php
- resources/lang/en/admin/clinic.php
- resources/lang/en/admin/user.php
- resources/views/admin/clinic_types/create.blade.php
- resources/views/admin/clinic_types/edit.blade.php
- resources/views/admin/clinic_types/index.blade.php
- resources/views/admin/clinics/create.blade.php
- resources/views/admin/clinics/edit.blade.php
- resources/views/admin/clinics/index.blade.php
- resources/views/admin/clinics/show.blade.php
- resources/views/admin/dashboard.blade.php
- resources/views/admin/layouts/app.blade.php
- resources/views/admin/users/index.blade.php
- resources/views/admin/users/show.blade.php
- routes/breadcrumbs.php
- routes/web.php
- tests/Browser/Pages/Admin/Users/ListUserPage.php
> Breadcrumb admin

- app/Http/Controllers/AdminClinic/ProfileController.php
- resources/lang/en/admin_clinic/breadcrumb.php
- resources/views/admin_clinic/appointments/index.blade.php
- resources/views/admin_clinic/appointments/show.blade.php
- resources/views/admin_clinic/calendar/index.blade.php
- resources/views/admin_clinic/dashboard.blade.php
- resources/views/admin_clinic/layouts/app.blade.php
- resources/views/admin_clinic/profile/edit/admin.blade.php
- resources/views/admin_clinic/profile/edit/clinic.blade.php
- resources/views/admin_clinic/profile/show.blade.php
- routes/breadcrumbs.php
Add breadcrumb for admin clinic page
NO
-
> Breadcrumb admin clinic

- app/Http/Controllers/API/User/AuthController.php
- app/Http/Requests/User/UserChangePassRequest.php
- app/Rules/AdminClinic/ExistedPassword.php
- docs/api-references/user.md
- resources/lang/en/api/user.php
- routes/api.php
- Write api user change password.
- Write api doc.
- Modify User doc
NO
-
> Api user change password

- app/ClinicImage.php
- app/Http/Controllers/API/User/ClinicController.php
- docs/api-references/clinic.md
Fix api clinic
update doc
NO
-
> fix api clinic

- app/Http/Controllers/User/ProfileController.php
- public/js/user/auth/logged.js
- public/js/user/profile.js
- resources/lang/en/user/breadcrumb.php
- resources/lang/en/user/layout.php
- resources/lang/en/user/profile.php
- resources/views/user/layouts/partials/navbar.blade.php
- resources/views/user/profile.blade.php
- routes/breadcrumbs.php
- routes/web.php
User view profile using api
NO
-
> user-view-profile

- app/Http/Controllers/API/User/AuthController.php
- docs/api-references/user.md
- public/js/user/auth/register.js
- resources/lang/en/api/user.php
- resources/views/user/layouts/partials/register.blade.php
- resources/views/user/register.blade.php
- Using register api
- Modify User api doc
- Task ID: TI-1
NO
-
> Register user using api

- app/Http/Controllers/API/User/ProfileController.php
- app/Http/Requests/User/UserUpdateProfileRequest.php
- docs/api-references/user.md
- resources/lang/en/api/user.php
- routes/api.php
- Api update user profile
- Write api doc
#{issue_id}
NO
-
> Api update user profile

- app/Http/Controllers/User/ProfileController.php
- public/js/user/change_password.js
- resources/lang/en/user/breadcrumb.php
- resources/lang/en/user/change_password.php
- resources/lang/en/user/layout.php
- resources/views/user/change_password.blade.php
- resources/views/user/layouts/partials/navbar.blade.php
- routes/api.php
- routes/breadcrumbs.php
- routes/web.php
> user change password

- app/Http/Controllers/User/ProfileController.php
- app/Http/Requests/User/UserUpdateProfileRequest.php
- public/js/user/edit_profile.js
- resources/lang/en/user/breadcrumb.php
- resources/lang/en/user/profile.php
- resources/views/user/edit_profile.blade.php
- routes/breadcrumbs.php
- routes/web.php
> user edit profile

- app/Appointment.php
- app/Http/Controllers/API/User/AppointmentController.php
- app/helpers.php
- composer.lock
- docs/api-references/appointment.md
- Api show list appointments of user.
- Write api doc
NO
-
> Api list appointments

- tests/Feature/API/GetListClinicsTest.php
- Test API show all clinics list (with filter) for user 
NO
-
> Test API clinics list

- app/Http/Controllers/API/User/AuthController.php
- app/User.php
- config/services.php
- database/migrations/2018_08_26_211432_add_provider_to_users_table.php
- docs/api-references/user.md
- public/js/user/auth/login.js
- resources/lang/en/api/user.php
- resources/views/user/login.blade.php
- routes/api.php
- add column `provider_id` in table `users`
- update `login.js`
- add login via facebook method
YES 
-
> user login facebook

- app/Appointment.php
- app/Http/Controllers/API/User/AppointmentController.php
- docs/api-references/appointment.md
- resources/lang/en/api/user.php
- routes/api.php
- Api user cancel pending or confirmed appointment
NO
-
> Api cancel appointment

- public/js/user/booking_appointment.js
- public/js/user/booking_datetime.js
- public/js/user/booking_success.js
- resources/lang/en/user/home.php
- resources/lang/en/user/layout.php
- resources/views/user/change_password.blade.php
- resources/views/user/edit_profile.blade.php
- resources/views/user/home.blade.php
- resources/views/user/layouts/partials/navbar.blade.php
- resources/views/user/layouts/partials/results.blade.php
- resources/views/user/profile.blade.php
- show more booking info
- fix layout profile, navbar, change password
NO
-
> fix/show more booking info, fix layout profile, navbar

- public/js/user/clinics_index.js
- public/js/user/custom/paginate.js
- resources/lang/en/user/filter.php
- resources/views/user/clinic/index.blade.php
- Redo pagination (non reload entire page when clicking pag index)
- Filter clinics user page
- Fix misc in render html for clinic item
NO
-
> Filter clinics user page

- public/css/user/custom.css
- public/js/user/appointments_index.js
- resources/lang/en/user/breadcrumb.php
- resources/views/user/appointment/index.blade.php
- resources/views/user/clinic/index.blade.php
- resources/views/user/clinic/show.blade.php
- routes/breadcrumbs.php
- Add breadcrumbs for clinic index and clinic detail page.
- Add link to clinic in list appointments
#83 
NO
-
> Add breadcrumbs
